apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
spec:
  containers:
  - name: girus
    image: ngnix
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}