apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
spec:
  containers:
  - name: girus
    image: ngnix
    resources: {}
  - name: busybox
    image: busybox
    args: 
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}