apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - name: webserver
    image: nginx
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-volume
    resources:
      limits:
        cpu: "1"
        memory: "128 Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-volume
    emptyDir:
      sizeLimit: 256Mi